# makefile generated by mcp2make 1.0.2

AS=armasm
CC=armcc
LD=armlink
FE=fromelf

ASFLAGS = -keep -g -apcs /interwork -cpu ARM920T -fpu None
CCFLAGS = -O1 -g+ -apcs /interwork -cpu ARM920T
LDFLAGS = -info totals -ro-base 0x32000000 -first 2440init.o(Init)
FEFLAGS = -c -bin -output 

OBJS = ledmain.o 2440slib.o 2440lib.o 2440init.o

all: led.axf
	@if exist *.axf echo Build completed

rebuild: clean all

clean:
	if exist *.o del *.o
	if exist *.axf del *.axf

led.axf: $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) -o led.axf
	$(FE) led.axf $(FEFLAGS) led.bin

ledmain.o: ledmain.c def.h option.h 2440addr.h 2440lib.h 2440slib.h
	$(CC) -c $(CCFLAGS) ledmain.c -o ledmain.o

2440slib.o: 2440slib.s
	$(AS) $(ASFLAGS) 2440slib.s -o 2440slib.o

2440lib.o: 2440lib.c def.h option.h 2440addr.h 2440lib.h 2440slib.h
	$(CC) -c $(CCFLAGS) 2440lib.c -o 2440lib.o

2440init.o: 2440init.s option.inc memcfg.inc 2440addr.inc
	$(AS) $(ASFLAGS) 2440init.s -o 2440init.o

